# Generated by Django 4.1 on 2023-12-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client_filter',
            field=models.JSONField(blank=True, default=dict, verbose_name='фильтр свойств клиентов'),
        ),
    ]
