# Generated by Django 4.1 on 2023-12-15 19:52

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_mailing_client_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET'),
        ),
    ]
