# Generated by Django 4.1.4 on 2023-12-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_client_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания (отправки)'),
        ),
    ]
